#!/usr/bin/env python3
import requests

def get_public_ip():
    response = requests.get('https://api.ipify.org').text
    return response
def main():
    print(get_public_ip())
if __name__ == "__main__":
    main()
